name: Tests
on:
  push:
    branches:
    - master

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  build:
    name: Run Unity tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - "2021.3.45f1"
          - "2022.3.55f1"
          - "6000.0.32f1"
    steps:
    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Cache
    - uses: actions/cache@v4
      with:
        path: Library
        key: Library-${{ runner.os }}-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
    
    # Run tests
    - name: Run tests
      uses: game-ci/unity-test-runner@v4
      with:
        unityVersion: ${{ matrix.unityVersion }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
